// This file has been generated by Tauri Specta. Do not edit this file manually.
export type SavedServer = {
	name: string,
	address: string,
	category?: string,
	/**
	 *  The client's last-pinged protocol for this server; owned by the
	 *  client, carried through so a launcher save doesn't strip it.
	 */
	protocol?: number | null,
};

export type ServerStatus = {
	online: boolean,
	players: number,
	max_players: number,
	ping_ms: number,
	motd: string,
	version: string,
};
