pub mod model;
pub mod registry;
pub mod sound;

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use azalea_block::BlockState;

use crate::physics::block_shape::{LocalBox, compute_shape};

/// Compact per-state property map: `(key, value)` pairs sorted by key. States
/// have at most ~10 properties, so binary search on a boxed slice beats a
/// `HashMap` in both footprint and lookup cost.
pub struct PropMap(Box<[(&'static str, &'static str)]>);

impl PropMap {
    fn from_pairs(mut pairs: Vec<(&'static str, &'static str)>) -> Self {
        pairs.sort_unstable_by_key(|&(k, _)| k);
        Self(pairs.into_boxed_slice())
    }

    pub fn get(&self, key: &str) -> Option<&'static str> {
        self.0
            .binary_search_by_key(&key, |&(k, _)| k)
            .ok()
            .map(|i| self.0[i].1)
    }

    pub fn entries(&self) -> impl Iterator<Item = (&'static str, &'static str)> + '_ {
        self.0.iter().copied()
    }
}

/// The two behavior fields the client reads (from vanilla `BlockBehaviour`).
#[derive(Clone, Copy)]
pub struct BlockBehavior {
    pub destroy_time: f32,
    pub requires_correct_tool_for_drops: bool,
}

const DEFAULT_BEHAVIOR: BlockBehavior = BlockBehavior {
    destroy_time: 0.0,
    requires_correct_tool_for_drops: false,
};

/// A face-occlusion shape projected onto the face plane as a 16x16 bit grid;
/// `mask[v]` holds row `v`'s bits. Generated by `just lightgen`.
pub type FaceMask = [u16; 16];

/// Per-state light properties (vanilla `BlockBehaviour.BlockStateBase`'s
/// baked light cache), loaded from the per-version table generated by
/// `tools/lightgen` running vanilla's own code.
#[derive(Clone, Copy)]
pub struct LightProps {
    pub emission: u8,
    pub dampening: u8,
    /// Unconsumed at runtime (vanilla only folds it into `dampening` at
    /// bake time); carried for parity with the vanilla property set.
    #[allow(dead_code)]
    pub propagates_skylight_down: bool,
    pub can_occlude: bool,
    pub use_shape_for_light_occlusion: bool,
    /// Per-face occlusion masks in vanilla `Direction` ordinal order (DOWN,
    /// UP, NORTH, SOUTH, WEST, EAST); `Some` exactly when `can_occlude &&
    /// use_shape_for_light_occlusion`.
    pub face_occlusion: Option<&'static [FaceMask; 6]>,
}

/// Unknown states occlude fully, matching vanilla's bedrock fallback for
/// out-of-range light-engine reads.
const BEDROCK_LIGHT: LightProps = LightProps {
    emission: 0,
    dampening: 15,
    propagates_skylight_down: false,
    can_occlude: true,
    use_shape_for_light_occlusion: false,
    face_occlusion: None,
};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FluidKind {
    Empty,
    Water,
    Lava,
}

/// Fluid content of a block state, matching vanilla `FluidState`: sources and
/// waterlogged blocks are amount 8; flowing fluid is `8 - level`; falling
/// fluid (level >= 8) renders/behaves as a full column.
#[derive(Clone, Copy)]
pub struct Fluid {
    pub kind: FluidKind,
    pub amount: u8,
    /// Not consumed yet; kept for vanilla parity (falling columns behave as
    /// full sources in flow/height logic).
    #[allow(dead_code)]
    pub falling: bool,
}

const NO_FLUID: Fluid = Fluid {
    kind: FluidKind::Empty,
    amount: 0,
    falling: false,
};

const FULL_WATER: Fluid = Fluid {
    kind: FluidKind::Water,
    amount: 8,
    falling: false,
};

impl Fluid {
    pub fn height(&self) -> f32 {
        self.amount as f32 / 9.0
    }
}

/// Per-state block data loaded from the per-version table generated by
/// `tools/blockgen` from Mojang's data-generator report. Hot paths (meshing
/// classifies and textures every block) index this directly.
struct BlockData {
    id: &'static str,
    properties: PropMap,
    behavior: BlockBehavior,
    /// Collision shape; see `block_shape::partial_shape` for the encoding.
    shape: Option<Box<[LocalBox]>>,
    is_air: bool,
    /// Vanilla `hasCollision`; precomputed so physics avoids name lookups.
    collides: bool,
    fluid: Fluid,
    light: LightProps,
}

#[derive(serde::Deserialize)]
struct BlockFile {
    version: String,
    state_count: u32,
    blocks: Vec<BlockEntry>,
}

// The data files also carry a `default_id` per block; nothing client-side
// consumes it yet, so serde skips it.
#[derive(serde::Deserialize)]
struct BlockEntry {
    name: String,
    first_id: u32,
    /// `(key, values)` in state-enumeration order; the last property varies
    /// fastest across consecutive state ids.
    #[serde(default)]
    props: Vec<(String, Vec<String>)>,
}

#[derive(serde::Deserialize)]
struct BehaviorEntry {
    destroy_time: f32,
    requires_correct_tool: bool,
}

#[derive(serde::Deserialize)]
struct LightFile {
    version: String,
    state_count: u32,
    /// Deduped face masks as 64-hex-char strings (16 rows of 4 chars).
    masks: Vec<String>,
    blocks: Vec<LightEntry>,
}

/// Per-block light fields; each is a scalar when uniform across the block's
/// states, else one value per state. `f` is 6 mask-dictionary indices —
/// a single tuple when uniform, else a per-state list of tuple-or-null.
#[derive(serde::Deserialize)]
struct LightEntry {
    name: String,
    e: ScalarOrPerState,
    d: ScalarOrPerState,
    p: ScalarOrPerState,
    o: ScalarOrPerState,
    u: ScalarOrPerState,
    #[serde(default)]
    f: Option<serde_json::Value>,
}

#[derive(serde::Deserialize)]
#[serde(untagged)]
enum ScalarOrPerState {
    One(u8),
    Many(Vec<u8>),
}

impl ScalarOrPerState {
    fn get(&self, offset: usize) -> u8 {
        match self {
            Self::One(v) => *v,
            Self::Many(vs) => vs[offset],
        }
    }
}

/// Per-protocol block-state data, latest first; unknown protocols fall back
/// to the latest (slot 0).
const BLOCK_DATA: [(i32, &str); 4] = [
    (
        pomme_protocol::version::LATEST.protocol,
        include_str!("data/blocks-26.2.json"),
    ),
    (775, include_str!("data/blocks-26.1.json")),
    (774, include_str!("data/blocks-1.21.11.json")),
    (773, include_str!("data/blocks-1.21.10.json")),
];

/// Light-property tables (`just lightgen`), index-aligned with [`BLOCK_DATA`].
const LIGHT_DATA: [&str; BLOCK_DATA.len()] = [
    include_str!("data/light-26.2.json"),
    include_str!("data/light-26.1.json"),
    include_str!("data/light-1.21.11.json"),
    include_str!("data/light-1.21.10.json"),
];

/// One lazily-built table per embedded data file; `ACTIVE_TABLE` indexes the
/// protocol currently spoken (see [`set_active_protocol`]).
static BLOCK_TABLES: [OnceLock<Vec<BlockData>>; BLOCK_DATA.len()] =
    [const { OnceLock::new() }; BLOCK_DATA.len()];
static ACTIVE_TABLE: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

/// Vanilla getFluidState overrides on blocks without a `waterlogged` property.
const IMPLICIT_WATER: [&str; 4] = ["seagrass", "tall_seagrass", "kelp", "kelp_plant"];

/// Blocks built with vanilla `noCollission()` (plus fluids/portals whose shape
/// is empty); consulted once per block at [`init`].
const NO_COLLISION: &[&str] = &[
    "acacia_hanging_sign",
    "acacia_pressure_plate",
    "acacia_sapling",
    "acacia_sign",
    "acacia_wall_hanging_sign",
    "acacia_wall_sign",
    "activator_rail",
    "air",
    "allium",
    "azure_bluet",
    "bamboo_hanging_sign",
    "bamboo_pressure_plate",
    "bamboo_sapling",
    "bamboo_sign",
    "bamboo_wall_hanging_sign",
    "bamboo_wall_sign",
    "beetroots",
    "big_dripleaf_stem",
    "birch_hanging_sign",
    "birch_pressure_plate",
    "birch_sapling",
    "birch_sign",
    "birch_wall_hanging_sign",
    "birch_wall_sign",
    "black_banner",
    "black_wall_banner",
    "blue_banner",
    "blue_orchid",
    "blue_wall_banner",
    "brain_coral",
    "brain_coral_fan",
    "brain_coral_wall_fan",
    "brown_banner",
    "brown_mushroom",
    "brown_wall_banner",
    "bubble_column",
    "bubble_coral",
    "bubble_coral_fan",
    "bubble_coral_wall_fan",
    "bush",
    "cactus_flower",
    "carrots",
    "cave_air",
    "cave_vines",
    "cave_vines_plant",
    "cherry_hanging_sign",
    "cherry_pressure_plate",
    "cherry_sapling",
    "cherry_sign",
    "cherry_wall_hanging_sign",
    "cherry_wall_sign",
    "closed_eyeblossom",
    "cobweb",
    "copper_torch",
    "copper_wall_torch",
    "cornflower",
    "crimson_fungus",
    "crimson_hanging_sign",
    "crimson_pressure_plate",
    "crimson_roots",
    "crimson_sign",
    "crimson_wall_hanging_sign",
    "crimson_wall_sign",
    "cyan_banner",
    "cyan_wall_banner",
    "dandelion",
    "dark_oak_hanging_sign",
    "dark_oak_pressure_plate",
    "dark_oak_sapling",
    "dark_oak_sign",
    "dark_oak_wall_hanging_sign",
    "dark_oak_wall_sign",
    "dead_brain_coral",
    "dead_brain_coral_fan",
    "dead_brain_coral_wall_fan",
    "dead_bubble_coral",
    "dead_bubble_coral_fan",
    "dead_bubble_coral_wall_fan",
    "dead_bush",
    "dead_fire_coral",
    "dead_fire_coral_fan",
    "dead_fire_coral_wall_fan",
    "dead_horn_coral",
    "dead_horn_coral_fan",
    "dead_horn_coral_wall_fan",
    "dead_tube_coral",
    "dead_tube_coral_fan",
    "dead_tube_coral_wall_fan",
    "detector_rail",
    "end_gateway",
    "end_portal",
    "fern",
    "fire",
    "fire_coral",
    "fire_coral_fan",
    "fire_coral_wall_fan",
    "firefly_bush",
    "frogspawn",
    "glow_lichen",
    "gray_banner",
    "gray_wall_banner",
    "green_banner",
    "green_wall_banner",
    "hanging_roots",
    "heavy_weighted_pressure_plate",
    "horn_coral",
    "horn_coral_fan",
    "horn_coral_wall_fan",
    "jungle_hanging_sign",
    "jungle_pressure_plate",
    "jungle_sapling",
    "jungle_sign",
    "jungle_wall_hanging_sign",
    "jungle_wall_sign",
    "kelp",
    "kelp_plant",
    "large_fern",
    "lava",
    "leaf_litter",
    "lever",
    "light_blue_banner",
    "light_blue_wall_banner",
    "light_gray_banner",
    "light_gray_wall_banner",
    "light_weighted_pressure_plate",
    "lilac",
    "lily_of_the_valley",
    "lime_banner",
    "lime_wall_banner",
    "magenta_banner",
    "magenta_wall_banner",
    "mangrove_hanging_sign",
    "mangrove_pressure_plate",
    "mangrove_propagule",
    "mangrove_sign",
    "mangrove_wall_hanging_sign",
    "mangrove_wall_sign",
    "nether_portal",
    "nether_sprouts",
    "nether_wart",
    "oak_hanging_sign",
    "oak_pressure_plate",
    "oak_sapling",
    "oak_sign",
    "oak_wall_hanging_sign",
    "oak_wall_sign",
    "open_eyeblossom",
    "orange_banner",
    "orange_tulip",
    "orange_wall_banner",
    "oxeye_daisy",
    "pale_hanging_moss",
    "pale_oak_hanging_sign",
    "pale_oak_pressure_plate",
    "pale_oak_sapling",
    "pale_oak_sign",
    "pale_oak_wall_hanging_sign",
    "pale_oak_wall_sign",
    "peony",
    "pink_banner",
    "pink_petals",
    "pink_tulip",
    "pink_wall_banner",
    "pitcher_crop",
    "pitcher_plant",
    "polished_blackstone_pressure_plate",
    "poppy",
    "potatoes",
    "powered_rail",
    "purple_banner",
    "purple_wall_banner",
    "rail",
    "red_banner",
    "red_mushroom",
    "red_tulip",
    "red_wall_banner",
    "redstone_torch",
    "redstone_wall_torch",
    "redstone_wire",
    "resin_clump",
    "rose_bush",
    "scaffolding",
    "sculk_vein",
    "seagrass",
    "short_dry_grass",
    "short_grass",
    "small_dripleaf",
    "soul_fire",
    "soul_torch",
    "soul_wall_torch",
    "spore_blossom",
    "spruce_hanging_sign",
    "spruce_pressure_plate",
    "spruce_sapling",
    "spruce_sign",
    "spruce_wall_hanging_sign",
    "spruce_wall_sign",
    "stone_pressure_plate",
    "structure_void",
    "sugar_cane",
    "sunflower",
    "sweet_berry_bush",
    "tall_dry_grass",
    "tall_grass",
    "tall_seagrass",
    "torch",
    "torchflower",
    "torchflower_crop",
    "tripwire",
    "tripwire_hook",
    "tube_coral",
    "tube_coral_fan",
    "tube_coral_wall_fan",
    "twisting_vines",
    "twisting_vines_plant",
    "vine",
    "void_air",
    "wall_torch",
    "warped_fungus",
    "warped_hanging_sign",
    "warped_pressure_plate",
    "warped_roots",
    "warped_sign",
    "warped_wall_hanging_sign",
    "warped_wall_sign",
    "water",
    "weeping_vines",
    "weeping_vines_plant",
    "wheat",
    "white_banner",
    "white_tulip",
    "white_wall_banner",
    "wildflowers",
    "wither_rose",
    "yellow_banner",
    "yellow_wall_banner",
];

/// Loads the block-state table for the launched game version. Must be called
/// once at startup before any world/render code runs.
pub fn init(version: &str) {
    let protocol = pomme_protocol::ProtocolVersion::from_name(version)
        .map(|v| v.protocol)
        .unwrap_or_else(|| {
            tracing::warn!(
                "no block-state data for version {version}, using 26.2 — expect state drift"
            );
            pomme_protocol::version::LATEST.protocol
        });
    set_active_protocol(protocol);
}

/// Switches the active table to the given protocol's, building it on first
/// use, so state ids from the wire are interpreted natively in that
/// version's id space (no chunk remapping). Patch releases sharing a
/// protocol number (26.1 through 26.1.2 are all 775) get the same table.
/// Only safe between worlds — meshes built against the previous table
/// interpret ids in the old id space.
pub fn set_active_protocol(protocol: i32) {
    let slot = prewarm_protocol(protocol);
    ACTIVE_TABLE.store(slot, std::sync::atomic::Ordering::Release);
}

/// Builds the given protocol's table if it isn't already, without switching
/// to it; safe at any time (e.g. from a server-list ping, ahead of the join).
pub fn prewarm_protocol(protocol: i32) -> usize {
    let slot = BLOCK_DATA
        .iter()
        .position(|&(p, _)| p == protocol)
        .unwrap_or(0);
    BLOCK_TABLES[slot].get_or_init(|| build_table(BLOCK_DATA[slot].1, LIGHT_DATA[slot]));
    slot
}

fn build_table(data: &str, light_data: &str) -> Vec<BlockData> {
    let file: BlockFile = serde_json::from_str(data).expect("invalid block-state data");
    let behaviors: HashMap<String, BehaviorEntry> =
        serde_json::from_str(include_str!("data/block_behavior.json"))
            .expect("invalid block-behavior data");
    let light_file: LightFile =
        serde_json::from_str(light_data).expect("invalid light-property data");
    assert_eq!(
        light_file.version, file.version,
        "light-property data is for a different version"
    );
    assert_eq!(
        light_file.state_count, file.state_count,
        "light-property data state count mismatch"
    );
    assert_eq!(
        light_file.blocks.len(),
        file.blocks.len(),
        "light-property data block count mismatch"
    );
    let masks: &'static [FaceMask] = Vec::leak(
        light_file
            .masks
            .iter()
            .map(|hex| decode_face_mask(hex))
            .collect(),
    );
    // The same handful of 6-mask tuples repeats across thousands of states;
    // dedupe them into leaked statics so each state stores one pointer.
    let mut tuples: HashMap<[u32; 6], &'static [FaceMask; 6]> = HashMap::new();
    let mut tuple = |indices: [u32; 6]| -> &'static [FaceMask; 6] {
        tuples
            .entry(indices)
            .or_insert_with(|| Box::leak(Box::new(indices.map(|i| masks[i as usize]))))
    };

    let mut interner: HashSet<&'static str> = HashSet::new();
    let mut intern = |s: &str| -> &'static str {
        match interner.get(s) {
            Some(&e) => e,
            None => {
                let leaked: &'static str = Box::leak(s.to_string().into_boxed_str());
                interner.insert(leaked);
                leaked
            }
        }
    };

    let mut table: Vec<BlockData> = Vec::with_capacity(file.state_count as usize);
    for (block, light_entry) in file.blocks.iter().zip(&light_file.blocks) {
        assert_eq!(
            block.first_id,
            table.len() as u32,
            "block-state data not dense at '{}'",
            block.name
        );
        assert_eq!(
            light_entry.name, block.name,
            "light-property data out of order at '{}'",
            block.name
        );
        let name = intern(&block.name);
        let behavior = match behaviors.get(&block.name) {
            Some(b) => BlockBehavior {
                destroy_time: b.destroy_time,
                requires_correct_tool_for_drops: b.requires_correct_tool,
            },
            None => {
                tracing::warn!("no behavior entry for block '{}', using defaults", name);
                DEFAULT_BEHAVIOR
            }
        };
        let props: Vec<(&'static str, Vec<&'static str>)> = block
            .props
            .iter()
            .map(|(k, vs)| (intern(k), vs.iter().map(|v| intern(v)).collect()))
            .collect();
        let is_air = matches!(block.name.as_str(), "air" | "cave_air" | "void_air");
        let collides = !NO_COLLISION.contains(&block.name.as_str());

        let count: u32 = props.iter().map(|(_, vs)| vs.len() as u32).product();
        let face_indices = light_face_indices(light_entry, count as usize);
        for offset in 0..count {
            let mut pairs = Vec::with_capacity(props.len());
            let mut stride = count;
            for (key, values) in &props {
                stride /= values.len() as u32;
                pairs.push((*key, values[(offset / stride) as usize % values.len()]));
            }
            let properties = PropMap::from_pairs(pairs);
            let fluid = state_fluid(name, &properties);
            let shape = compute_shape(name, &properties).map(Vec::into_boxed_slice);
            let light = LightProps {
                emission: light_entry.e.get(offset as usize),
                dampening: light_entry.d.get(offset as usize),
                propagates_skylight_down: light_entry.p.get(offset as usize) != 0,
                can_occlude: light_entry.o.get(offset as usize) != 0,
                use_shape_for_light_occlusion: light_entry.u.get(offset as usize) != 0,
                face_occlusion: face_indices[offset as usize].map(&mut tuple),
            };
            table.push(BlockData {
                id: name,
                properties,
                behavior,
                shape,
                is_air,
                collides,
                fluid,
                light,
            });
        }
    }

    assert_eq!(
        table.len() as u32,
        file.state_count,
        "block-state data table size mismatch for {}",
        file.version
    );
    table
}

fn decode_face_mask(hex: &str) -> FaceMask {
    assert_eq!(hex.len(), 64, "face mask must be 64 hex chars");
    std::array::from_fn(|v| {
        u16::from_str_radix(&hex[v * 4..v * 4 + 4], 16).expect("invalid face-mask hex")
    })
}

/// Expands a light entry's `f` field into per-state mask-dictionary tuples.
fn light_face_indices(entry: &LightEntry, count: usize) -> Vec<Option<[u32; 6]>> {
    let Some(f) = &entry.f else {
        return vec![None; count];
    };
    let arr = f
        .as_array()
        .unwrap_or_else(|| panic!("{}: face-mask field is not an array", entry.name));
    let parse_tuple = |values: &[serde_json::Value]| -> [u32; 6] {
        assert_eq!(values.len(), 6, "{}: face-mask tuple length", entry.name);
        std::array::from_fn(|i| {
            values[i]
                .as_u64()
                .unwrap_or_else(|| panic!("{}: non-numeric face-mask index", entry.name))
                as u32
        })
    };
    if arr.first().is_some_and(serde_json::Value::is_number) {
        // Uniform across the block: a single 6-index tuple.
        return vec![Some(parse_tuple(arr)); count];
    }
    assert_eq!(arr.len(), count, "{}: face-mask entry count", entry.name);
    arr.iter()
        .map(|v| {
            if v.is_null() {
                None
            } else {
                Some(parse_tuple(v.as_array().unwrap_or_else(|| {
                    panic!("{}: face-mask entry is not a tuple", entry.name)
                })))
            }
        })
        .collect()
}

fn state_fluid(name: &'static str, props: &PropMap) -> Fluid {
    match name {
        "water" | "lava" => {
            let level: u8 = props.get("level").and_then(|l| l.parse().ok()).unwrap_or(0);
            let kind = if name == "water" {
                FluidKind::Water
            } else {
                FluidKind::Lava
            };
            if level >= 8 {
                Fluid {
                    kind,
                    amount: 8,
                    falling: true,
                }
            } else {
                Fluid {
                    kind,
                    amount: 8 - level,
                    falling: false,
                }
            }
        }
        "bubble_column" => FULL_WATER,
        _ if IMPLICIT_WATER.contains(&name) => FULL_WATER,
        _ if props.get("waterlogged") == Some("true") => FULL_WATER,
        _ => NO_FLUID,
    }
}

fn table() -> &'static Vec<BlockData> {
    BLOCK_TABLES[ACTIVE_TABLE.load(std::sync::atomic::Ordering::Acquire)]
        .get()
        .expect("world::block::init must be called before use")
}

fn block_data(state: BlockState) -> &'static BlockData {
    static UNKNOWN: std::sync::LazyLock<BlockData> = std::sync::LazyLock::new(|| BlockData {
        id: "unknown",
        properties: PropMap::from_pairs(Vec::new()),
        behavior: DEFAULT_BEHAVIOR,
        shape: None,
        is_air: false,
        collides: true,
        fluid: NO_FLUID,
        light: BEDROCK_LIGHT,
    });
    table().get(u32::from(state) as usize).unwrap_or(&UNKNOWN)
}

/// Every valid block state paired with its cached data, in id order.
fn all_states() -> impl Iterator<Item = (BlockState, &'static BlockData)> {
    table().iter().enumerate().map(|(id, data)| {
        let state = BlockState::try_from(id as u32).expect("table indices fit the id repr");
        (state, data)
    })
}

/// First declared state of the named block, e.g. the light engine's bedrock
/// fallback for unloaded-chunk reads.
pub(crate) fn first_state_of(name: &str) -> Option<BlockState> {
    all_states().find(|(_, d)| d.id == name).map(|(s, _)| s)
}

/// Converts a wire-side numeric state id, validated against the loaded table.
pub fn try_state(id: u32) -> Option<BlockState> {
    if (id as usize) < table().len() {
        BlockState::try_from(id).ok()
    } else {
        None
    }
}

pub fn block_id(state: BlockState) -> &'static str {
    block_data(state).id
}

pub fn block_properties(state: BlockState) -> &'static PropMap {
    &block_data(state).properties
}

pub fn block_behavior(state: BlockState) -> &'static BlockBehavior {
    &block_data(state).behavior
}

/// Vanilla `isAir`: includes cave and void air.
pub fn is_air(state: BlockState) -> bool {
    block_data(state).is_air
}

/// Whether the state's block collides with entities (vanilla `hasCollision`).
pub fn has_collision(state: BlockState) -> bool {
    block_data(state).collides
}

pub fn fluid(state: BlockState) -> Fluid {
    block_data(state).fluid
}

pub(crate) fn block_shape(state: BlockState) -> Option<&'static [LocalBox]> {
    block_data(state).shape.as_deref()
}

/// Baked light properties for a state (vanilla `BlockStateBase` light cache).
pub fn light_props(state: BlockState) -> LightProps {
    block_data(state).light
}

/// Vanilla `LightEngine.isEmptyShape`: the state needs no voxel-shape
/// occlusion tests (full opaque cubes qualify — their opacity handles them).
pub fn is_empty_shape(state: BlockState) -> bool {
    let light = block_data(state).light;
    !light.can_occlude || !light.use_shape_for_light_occlusion
}

/// Vanilla `LightEngine.shapeOccludes(from, to, dir)` reduced to face masks:
/// whether `from`'s face and `to`'s opposite face together cover the full
/// face. `face` is the vanilla `Direction` ordinal (DOWN, UP, NORTH, SOUTH,
/// WEST, EAST); opposites pair as `face ^ 1`. Empty-shape states contribute
/// an empty mask, so two shapeless neighbors never occlude.
pub fn shape_occludes(from: BlockState, to: BlockState, face: usize) -> bool {
    let mask = |state: BlockState, face: usize| {
        block_data(state)
            .light
            .face_occlusion
            .map(|masks| &masks[face])
    };
    let a = mask(from, face);
    let b = mask(to, face ^ 1);
    if a.is_none() && b.is_none() {
        return false;
    }
    (0..16).all(|v| (a.map_or(0, |m| m[v]) | b.map_or(0, |m| m[v])) == 0xFFFF)
}

/// The block's state matching the given property values (unlisted properties
/// take whatever the first match has); shared with the light-engine tests.
#[cfg(test)]
pub(crate) fn find_state(name: &str, props: &[(&str, &str)]) -> BlockState {
    all_states()
        .find(|(s, d)| {
            d.id == name
                && props
                    .iter()
                    .all(|&(k, v)| block_properties(*s).get(k) == Some(v))
        })
        .unwrap_or_else(|| panic!("no state {name} {props:?}"))
        .0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() {
        init("26.2");
    }

    #[test]
    fn chest_states_decode() {
        setup();
        // Oracle from reference/26.2/generated/reports/blocks.json:
        // chest[type=single,facing=south,waterlogged=false] is id 3994 — the
        // state that previously decoded as facing=east under azalea's stale
        // 26.1 tables.
        let state = try_state(3994).unwrap();
        assert_eq!(block_id(state), "chest");
        let props = block_properties(state);
        assert_eq!(props.get("facing"), Some("south"));
        assert_eq!(props.get("type"), Some("single"));
        assert_eq!(props.get("waterlogged"), Some("false"));
    }

    #[test]
    fn new_26_2_blocks_resolve() {
        setup();
        assert!(all_states().any(|(_, d)| d.id == "copper_chest"));
        assert!(try_state(u32::MAX).is_none());
        let count = table().len() as u32;
        assert!(try_state(count).is_none());
        assert!(try_state(count - 1).is_some());
    }

    #[test]
    fn fluid_states() {
        setup();
        let (still, _) = all_states()
            .find(|(s, d)| d.id == "water" && block_properties(*s).get("level") == Some("0"))
            .unwrap();
        let f = fluid(still);
        assert_eq!(f.kind, FluidKind::Water);
        assert_eq!(f.amount, 8);
        assert!(!f.falling);

        let (falling, _) = all_states()
            .find(|(s, d)| d.id == "water" && block_properties(*s).get("level") == Some("9"))
            .unwrap();
        assert!(fluid(falling).falling);

        let (logged, _) = all_states()
            .find(|(s, d)| {
                d.id == "oak_stairs" && block_properties(*s).get("waterlogged") == Some("true")
            })
            .unwrap();
        assert_eq!(fluid(logged).kind, FluidKind::Water);
        assert_eq!(fluid(logged).amount, 8);

        assert_eq!(fluid(BlockState::AIR).kind, FluidKind::Empty);
    }

    #[test]
    fn light_emission_values() {
        setup();
        // Oracles from reference/26.2/decompiled Blocks.java lightLevel sites.
        assert_eq!(light_props(find_state("torch", &[])).emission, 14);
        assert_eq!(light_props(find_state("glowstone", &[])).emission, 15);
        assert_eq!(
            light_props(find_state("redstone_lamp", &[("lit", "true")])).emission,
            15
        );
        assert_eq!(
            light_props(find_state("redstone_lamp", &[("lit", "false")])).emission,
            0
        );
        assert_eq!(
            light_props(find_state(
                "sea_pickle",
                &[("pickles", "3"), ("waterlogged", "true")]
            ))
            .emission,
            12
        );
        assert_eq!(
            light_props(find_state(
                "sea_pickle",
                &[("pickles", "3"), ("waterlogged", "false")]
            ))
            .emission,
            0
        );
        assert_eq!(
            light_props(find_state("cave_vines", &[("berries", "true")])).emission,
            14
        );
        assert_eq!(
            light_props(find_state("cave_vines", &[("berries", "false")])).emission,
            0
        );
        assert_eq!(
            light_props(find_state("light", &[("level", "7")])).emission,
            7
        );
    }

    #[test]
    fn light_dampening_values() {
        setup();
        let stone = light_props(find_state("stone", &[]));
        assert_eq!(stone.dampening, 15);
        assert!(stone.can_occlude);
        assert!(!stone.use_shape_for_light_occlusion);
        assert!(is_empty_shape(find_state("stone", &[])));

        assert_eq!(
            light_props(find_state("water", &[("level", "0")])).dampening,
            1
        );
        assert_eq!(light_props(find_state("oak_leaves", &[])).dampening, 1);
        let glass = light_props(find_state("glass", &[]));
        assert_eq!(glass.dampening, 0);
        assert!(glass.propagates_skylight_down);
        assert_eq!(light_props(BlockState::AIR).dampening, 0);
    }

    #[test]
    fn slab_face_occlusion() {
        setup();
        let top = find_state("oak_slab", &[("type", "top"), ("waterlogged", "false")]);
        let bottom = find_state("oak_slab", &[("type", "bottom"), ("waterlogged", "false")]);
        let double = find_state("oak_slab", &[("type", "double")]);
        let stone = find_state("stone", &[]);

        assert!(!is_empty_shape(top));
        assert!(!is_empty_shape(bottom));
        // Double slabs are solid-render full cubes: no shape tests needed.
        assert!(is_empty_shape(double));

        // Vanilla Direction ordinals: DOWN=0, UP=1.
        const DOWN: usize = 0;
        const UP: usize = 1;
        // A top slab's UP face is full; a bottom slab's DOWN face is full.
        assert!(shape_occludes(top, stone, UP));
        assert!(shape_occludes(bottom, stone, DOWN));
        // The open halves don't occlude.
        assert!(!shape_occludes(top, stone, DOWN));
        assert!(!shape_occludes(bottom, stone, UP));
        // Top slab above a bottom slab: neither shape touches the seam plane,
        // so both face slices are empty and the seam stays open.
        assert!(!shape_occludes(top, bottom, DOWN));
        const NORTH: usize = 2;
        // Side faces of two aligned bottom slabs cover only the lower half.
        assert!(!shape_occludes(bottom, bottom, NORTH));
    }

    /// Builds every embedded table so the block/light cross-checks fire for
    /// all versions, not just the one `setup` activates.
    #[test]
    fn all_tables_build() {
        for (slot, (_, data)) in BLOCK_DATA.iter().enumerate() {
            build_table(data, LIGHT_DATA[slot]);
        }
    }
}
