//! Per-version tables of the client-facing static registries and the
//! cross-version id remaps built from them.
//!
//! Static-registry ids (entities, sounds, items, ...) are implicit from
//! registration order and shift between game versions. The tables are the
//! ordered entry names (wire id == index) generated by
//! `tools/protogen registries` from the data-generator reports; a remap
//! translates an older version's ids into the latest version's id space so
//! the rest of the client stays single-version.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::version::{EMBEDDED, LATEST, ProtocolVersion};

/// The registries carried in `registries-<version>.json` (matching
/// protogen's `CLIENT_REGISTRIES`): the ones whose numeric ids reach the
/// client inside game packets.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ClientRegistry {
    Attribute,
    BlockEntityType,
    DataComponentType,
    EntityType,
    GameEvent,
    Item,
    ParticleType,
    SoundEvent,
}

impl ClientRegistry {
    pub const ALL: [ClientRegistry; 8] = [
        ClientRegistry::Attribute,
        ClientRegistry::BlockEntityType,
        ClientRegistry::DataComponentType,
        ClientRegistry::EntityType,
        ClientRegistry::GameEvent,
        ClientRegistry::Item,
        ClientRegistry::ParticleType,
        ClientRegistry::SoundEvent,
    ];

    fn key(self) -> &'static str {
        match self {
            ClientRegistry::Attribute => "attribute",
            ClientRegistry::BlockEntityType => "block_entity_type",
            ClientRegistry::DataComponentType => "data_component_type",
            ClientRegistry::EntityType => "entity_type",
            ClientRegistry::GameEvent => "game_event",
            ClientRegistry::Item => "item",
            ClientRegistry::ParticleType => "particle_type",
            ClientRegistry::SoundEvent => "sound_event",
        }
    }
}

/// One version's ordered registry entry names (wire id == index).
pub struct RegistryTable {
    version: ProtocolVersion,
    registries: [Vec<String>; ClientRegistry::ALL.len()],
}

#[derive(serde::Deserialize)]
struct TableFile {
    version: String,
    protocol: i32,
    registries: HashMap<String, Vec<String>>,
}

impl RegistryTable {
    pub fn latest() -> &'static RegistryTable {
        static TABLE: OnceLock<RegistryTable> = OnceLock::new();
        TABLE.get_or_init(|| {
            Self::parse(include_str!("data/registries-26.2.json"), LATEST)
                .expect("embedded 26.2 registry table")
        })
    }

    /// The table for a launchable protocol number, or `None` for versions
    /// without an embedded table.
    pub fn for_protocol(protocol: i32) -> Option<&'static RegistryTable> {
        if protocol == LATEST.protocol {
            return Some(Self::latest());
        }
        static TABLES: [OnceLock<RegistryTable>; EMBEDDED.len()] =
            [const { OnceLock::new() }; EMBEDDED.len()];
        crate::version::embedded_get(protocol, &TABLES, |e| {
            Self::parse(e.registries, e.version)
                .unwrap_or_else(|err| panic!("embedded {} registry table: {err}", e.version.name))
        })
    }

    fn parse(json: &str, expected: ProtocolVersion) -> Result<Self, String> {
        let mut file: TableFile = serde_json::from_str(json).map_err(|e| e.to_string())?;
        if file.version != expected.name || file.protocol != expected.protocol {
            return Err(format!(
                "table is {}/{}, expected {}/{}",
                file.version, file.protocol, expected.name, expected.protocol
            ));
        }
        let mut registries: [Vec<String>; ClientRegistry::ALL.len()] = Default::default();
        for reg in ClientRegistry::ALL {
            let names = file
                .registries
                .remove(reg.key())
                .ok_or_else(|| format!("missing registry {}", reg.key()))?;
            if names.is_empty() {
                return Err(format!("empty registry {}", reg.key()));
            }
            registries[reg as usize] = names;
        }
        Ok(Self {
            version: expected,
            registries,
        })
    }

    pub fn version(&self) -> ProtocolVersion {
        self.version
    }

    pub fn names(&self, reg: ClientRegistry) -> &[String] {
        &self.registries[reg as usize]
    }

    pub fn name_of(&self, reg: ClientRegistry, id: u32) -> Option<&str> {
        self.names(reg).get(id as usize).map(String::as_str)
    }
}

/// Directed id remaps between two versions' registries, matched by entry
/// name. `None` marks ids without an equivalent in the target version
/// (entries added/removed since, or out of range).
pub struct RegistryRemaps {
    maps: [Vec<Option<u32>>; ClientRegistry::ALL.len()],
}

impl RegistryRemaps {
    /// Remaps from `protocol`'s id space to the latest version's (for
    /// inbound packets), or `None` for versions without an embedded registry
    /// table. For the latest version itself this is an identity map.
    pub fn to_latest(protocol: i32) -> Option<&'static RegistryRemaps> {
        if protocol == LATEST.protocol {
            return Some(Self::identity());
        }
        static REMAPS: [OnceLock<RegistryRemaps>; EMBEDDED.len()] =
            [const { OnceLock::new() }; EMBEDDED.len()];
        crate::version::embedded_get(protocol, &REMAPS, |_| {
            Self::build(Self::embedded_table(protocol), RegistryTable::latest())
        })
    }

    /// Remaps from the latest version's id space to `protocol`'s (for
    /// outbound packets); the mirror of [`Self::to_latest`].
    pub fn from_latest(protocol: i32) -> Option<&'static RegistryRemaps> {
        if protocol == LATEST.protocol {
            return Some(Self::identity());
        }
        static REMAPS: [OnceLock<RegistryRemaps>; EMBEDDED.len()] =
            [const { OnceLock::new() }; EMBEDDED.len()];
        crate::version::embedded_get(protocol, &REMAPS, |_| {
            Self::build(RegistryTable::latest(), Self::embedded_table(protocol))
        })
    }

    fn embedded_table(protocol: i32) -> &'static RegistryTable {
        RegistryTable::for_protocol(protocol).expect("embedded registry table")
    }

    fn identity() -> &'static RegistryRemaps {
        static IDENTITY: OnceLock<RegistryRemaps> = OnceLock::new();
        IDENTITY.get_or_init(|| Self::build(RegistryTable::latest(), RegistryTable::latest()))
    }

    fn build(from: &RegistryTable, to: &RegistryTable) -> Self {
        let maps = ClientRegistry::ALL.map(|reg| {
            let to_ids: HashMap<&str, u32> = to
                .names(reg)
                .iter()
                .enumerate()
                .map(|(id, name)| (name.as_str(), id as u32))
                .collect();
            from.names(reg)
                .iter()
                .map(|name| to_ids.get(name.as_str()).copied())
                .collect()
        });
        Self { maps }
    }

    /// The target-version id for `id` in the source version's `reg`, or
    /// `None` if the entry has no equivalent (callers drop or ignore those).
    pub fn remap(&self, reg: ClientRegistry, id: u32) -> Option<u32> {
        self.maps[reg as usize].get(id as usize).copied().flatten()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The remap under test plus its endpoint tables.
    fn setup(
        protocol: i32,
    ) -> (
        &'static RegistryRemaps,
        &'static RegistryTable,
        &'static RegistryTable,
    ) {
        (
            RegistryRemaps::to_latest(protocol).unwrap(),
            RegistryTable::for_protocol(protocol).unwrap(),
            RegistryTable::latest(),
        )
    }

    /// The bed block entity was removed in 26.2; its id has no remap.
    fn assert_bed_unmapped(r: &RegistryRemaps, from: &RegistryTable) {
        let bed = from
            .names(ClientRegistry::BlockEntityType)
            .iter()
            .position(|n| n == "bed")
            .unwrap() as u32;
        assert_eq!(r.remap(ClientRegistry::BlockEntityType, bed), None);
    }

    /// Every remapped id resolves to the same entry name in the target table.
    fn assert_round_trips(r: &RegistryRemaps, from: &RegistryTable, to: &RegistryTable) {
        for reg in ClientRegistry::ALL {
            for (id, name) in from.names(reg).iter().enumerate() {
                if let Some(new_id) = r.remap(reg, id as u32) {
                    assert_eq!(to.name_of(reg, new_id), Some(name.as_str()), "{reg:?} {id}");
                }
            }
        }
    }

    /// Anchors hand-checked against the 26.1/26.2 `registries.json` report
    /// diff (insertion points and the one removed entry).
    #[test]
    fn remap_26_1_anchors() {
        let (r, from, to) = setup(775);

        // 26.2 inserted air_drag_modifier at attribute id 0.
        assert_eq!(from.name_of(ClientRegistry::Attribute, 0), Some("armor"));
        assert_eq!(to.name_of(ClientRegistry::Attribute, 1), Some("armor"));
        assert_eq!(r.remap(ClientRegistry::Attribute, 0), Some(1));

        // 26.2 inserted sulfur_cube at entity id 130; ids below are stable.
        assert_eq!(
            from.name_of(ClientRegistry::EntityType, 130),
            Some("tadpole")
        );
        assert_eq!(r.remap(ClientRegistry::EntityType, 129), Some(129));
        assert_eq!(r.remap(ClientRegistry::EntityType, 130), Some(131));

        assert_bed_unmapped(r, from);

        // Particle ids diverge right after bubble (id 3 in both).
        assert_eq!(r.remap(ClientRegistry::ParticleType, 3), Some(3));
        assert_eq!(from.name_of(ClientRegistry::ParticleType, 4), Some("cloud"));
        assert_eq!(
            to.name_of(ClientRegistry::ParticleType, 4),
            Some("sulfur_bubbles")
        );
        assert_ne!(r.remap(ClientRegistry::ParticleType, 4), Some(4));

        // Out-of-range source ids don't remap.
        assert_eq!(r.remap(ClientRegistry::SoundEvent, 100_000), None);

        assert_round_trips(r, from, to);
    }

    /// Anchor checks against the 1.21.11 -> 26.2 registry diff (spot-checked
    /// by hand against the two data-generator reports).
    #[test]
    fn remap_1_21_11_anchors() {
        let (r, from, to) = setup(774);

        // 26.x inserted air_drag_modifier at attribute id 0.
        assert_eq!(from.name_of(ClientRegistry::Attribute, 0), Some("armor"));
        assert_eq!(r.remap(ClientRegistry::Attribute, 0), Some(1));

        // sulfur_cube landed at entity id 130; ids below are stable.
        assert_eq!(
            from.name_of(ClientRegistry::EntityType, 130),
            Some("tadpole")
        );
        assert_eq!(r.remap(ClientRegistry::EntityType, 129), Some(129));
        assert_eq!(r.remap(ClientRegistry::EntityType, 130), Some(131));

        assert_bed_unmapped(r, from);

        // Particle ids diverge right after bubble (id 3 in both).
        assert_eq!(r.remap(ClientRegistry::ParticleType, 3), Some(3));
        assert_ne!(r.remap(ClientRegistry::ParticleType, 4), Some(4));

        // Component ids diverge at 41, where 26.x inserted
        // additional_trade_cost; this is where inbound item components start
        // decoding under the wrong codec (see translate.rs).
        assert_eq!(
            from.name_of(ClientRegistry::DataComponentType, 41),
            Some("stored_enchantments")
        );
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 40), Some(40));
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 41), Some(42));

        assert_round_trips(r, from, to);
    }

    /// Anchor checks against the 1.21.10 -> 26.2 registry diff (spot-checked
    /// by hand against the two data-generator reports). 1.21.11 added the
    /// nautilus/spear content drop, so 1.21.10 diverges earlier than 1.21.11
    /// in several registries.
    #[test]
    fn remap_1_21_10_anchors() {
        let (r, from, to) = setup(773);

        // 26.x inserted air_drag_modifier at attribute id 0.
        assert_eq!(from.name_of(ClientRegistry::Attribute, 0), Some("armor"));
        assert_eq!(r.remap(ClientRegistry::Attribute, 0), Some(1));

        // Entity ids diverge at 20, where 1.21.11 inserted camel_husk.
        assert_eq!(from.name_of(ClientRegistry::EntityType, 20), Some("cat"));
        assert_eq!(r.remap(ClientRegistry::EntityType, 19), Some(19));
        assert_eq!(r.remap(ClientRegistry::EntityType, 20), Some(21));
        assert_eq!(r.remap(ClientRegistry::EntityType, 127), Some(131)); // tadpole

        assert_bed_unmapped(r, from);

        // Particle ids diverge right after bubble (id 3 in both).
        assert_eq!(r.remap(ClientRegistry::ParticleType, 3), Some(3));
        assert_ne!(r.remap(ClientRegistry::ParticleType, 4), Some(4));

        // Component ids diverge at 5, where 1.21.11 inserted use_effects —
        // far earlier than 1.21.11's divergence at 41, so the raw item-stack
        // limitation (see translate.rs) covers common components like
        // custom_name and enchantments on this version.
        assert_eq!(
            from.name_of(ClientRegistry::DataComponentType, 5),
            Some("custom_name")
        );
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 4), Some(4));
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 5), Some(6));

        assert_round_trips(r, from, to);
    }

    #[test]
    fn latest_identity() {
        let r = RegistryRemaps::to_latest(LATEST.protocol).unwrap();
        let names = RegistryTable::latest().names(ClientRegistry::SoundEvent);
        assert_eq!(
            r.remap(ClientRegistry::SoundEvent, names.len() as u32 - 1),
            Some(names.len() as u32 - 1)
        );
    }
}
