#version 450

// chunk.vert variant for the water pass: `draw_water` records one draw per
// section CPU-side, so the section origin and fade arrive as push constants
// instead of the per-instance meta attributes the indirect passes use.

#include "fog.glsl"

layout(set = 0, binding = 0) uniform CameraUniform {
    mat4 view_proj;
    vec4 camera_pos;
    vec4 fog_color;
};

// POS_RANGE / POS_BIAS, generated by build.rs from packing_consts.rs.
#include "packing.glsl"

layout(push_constant) uniform SectionPc {
    // xyz = section origin relative to the camera anchor (rebased in f64
    // CPU-side), w = fade.
    vec4 origin_fade;
};

layout(location = 0) in vec2 in_pos_xy;
layout(location = 1) in float in_pos_z;
layout(location = 2) in vec2 tex_coords;
layout(location = 3) in vec4 light_tint;

layout(location = 0) out vec2 v_tex_coords;
layout(location = 1) out float v_light;
layout(location = 2) out vec3 v_tint;
layout(location = 3) flat out float v_visibility;
layout(location = 4) out vec3 v_fog_color;
layout(location = 5) out float v_fog;

void main() {
    vec3 local = vec3(in_pos_xy, in_pos_z) * POS_RANGE - POS_BIAS;
    vec3 world = origin_fade.xyz + local;
    vec3 rel = world - camera_pos.xyz;
    gl_Position = view_proj * vec4(rel, 1.0);
    v_tex_coords = tex_coords;
    v_light = light_tint.r;
    v_tint = light_tint.gba;
    v_visibility = origin_fade.w;
    v_fog_color = fog_color.rgb;
    v_fog = fog_factor(rel, camera_pos.w, fog_color.w);
}
